version: '3.6'

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  db:
    driver: local

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'true' 
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_ADMIN_ENABLE_SERVER: 'false'

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:${KAFKA_PORT},DOCKERINTERNAL://kafka:19092'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,DOCKERINTERNAL://:19092'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'DOCKERINTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKERINTERNAL
    links:
      - zookeeper

  akhq:
    container_name: akqh
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:19092"
    ports:
      - ${AKQH_PORT}:8080
    links:
      - kafka

  db:
    container_name: mysql-db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: Mulesoft
      MYSQL_DATABASE: myDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "${MYSQL_PORT}:3306"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on: 
      - db